name = "kodama"
description = "Theme insipired by wowchemy academic."
license = "MIT"
homepage = "https://github.com/adfaure/kodama-theme"
# The minimum version of Zola required
min_version = "0.15"

# An optional live demo URL
demo = "https://adfaure.github.io/kodama-theme/"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "Adrien Faure"
homepage = "https://adrien-faure.fr"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "Geogre Cushen"
homepage = "https://themes.gohugo.io/themes/hugo-academic/"
repo = "https://github.com/wowchemy/wowchemy-hugo-themes"
